Do not record non-sampled spans
lightstep/lightstep-tracer-python pull request #109
Opened 2020-09-17 16:25 UTC by ocelotl

Fixes #108

2020-09-17 22:21 UTC, codeboten requested changes
Great! Please update the changelog

2020-09-17 23:42 UTC, codeboten approved these changes

2020-09-18 04:49 UTC, kayousterhout approved these changes
Thanks for fixing this!

2020-09-18 15:52 UTC, merged

2020-09-18 16:58 UTC, ikonst commented
Thanks @ocelotl!